name: Release

on:
  repository_dispatch:
    types: [release]
  workflow_run:
    workflows:
      - SharpHound
      - Rubeus
      - Certify
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        id: preparing
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.1'
          architecture: 'x64'

      - name: Download Artifacts
        run: |
          pip install -r requirements.txt
          python build/release.py ${{ github.token }}
      - name: Push Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: kebab
          files: .tmp/*
