name: Release

on:
  repository_dispatch:
    types: [completchef, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        id: preparing
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.1'
          architecture: 'x64'
      - name: Download Artifacts
        run: |
          pip install -r requirements.txt
          paths=$(python my_script.py ${{ github.token }})
          echo "::set-output name=BINARIES::$paths"
      - name: Push Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: "kebab"
          files: |
            ${{ steps.binaries.outputs.BINARIES }}